spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/springdb
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://herokutest.ci3casdwagpp.ap-south-1.rds.amazonaws.com/aws
   username: admin
   password: mypassword
  jpa:
    hibernate:      ddl-auto: update
    show-sql: true
    
server:  port: 8959
 
logging:  level:    '[org.springframework.security]': DEBUG